### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sebastiandeutsch** [FirzenYogesh/FileListerDialog#1]
Hi, this is Sebastian from AndroidWeekly. Could you please choose a license? Also a screenshot would be very nice.

**Comment by FirzenYogesh** [comment]
@sebastiandeutsch Hi, I have updated the repo with the License and added screenshots to the library please do check, Thank you.

**Comment by sebastiandeutsch** [comment]
Thank you - also for open sourcing your library.
