### ISSUE TITLE
Change the color of the Folder and text

### ISSUE THREAD

**Issue by johncodeos** [FirzenYogesh/FileListerDialog#5]
Hi,
Is there any way to change the color of the folder icon and text of folder/file or take the same color as dialog's buttons?

**Comment by FirzenYogesh** [comment]
Hello you can change the icon and text color by using this

`<style name="FileListerItemColor">
        <item name="android:textColor">@android:color/white</item>
        <item name="android:tint">#4CAF50</item>
    </style>
`

**Comment by johncodeos** [comment]
Yeah, I found that, but I want to change it programmatically because my app uses Themes. So for example if the Theme is black, I want to change folder icons and text to white.

**Comment by FirzenYogesh** [comment]
yes i will be updating the Library soon with that feature

**Comment by johncodeos** [comment]
Ok thanks!
