### ISSUE TITLE
Error when selecting a folder

### ISSUE THREAD

**Issue by nikitagudkovs** [FirzenYogesh/FileListerDialog#9]
When I select a folder in the dialog, app crashes with: 

> Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.io.FilenameUtils" on path: DexPathList[[zip file "/data/app/com.myApp-F0_sdB_QRzZKIKky8gOrAA==/base.apk"],nativeLibraryDirectories=[/data/app/com.myApp-F0_sdB_QRzZKIKky8gOrAA==/lib/arm64, /data/app/com.myApp-F0_sdB_QRzZKIKky8gOrAA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]

I have apache commons library imposed in my project.
Any ideas what could cause that?

**Comment by nikitagudkovs** [comment]
Sorry, had wrong commons imported

**Comment by nikitagudkovs** [comment]
PLease add to description that library also depends on 'org.apache.commons:commons-io:1.3.2'

**Comment by FirzenYogesh** [comment]
thank you i have added the library dependency in the description
